CREATE DATABASE IF NOT EXISTS organdb;
USE organdb;

CREATE TABLE IF NOT EXISTS registration (
    REGISTRATION_ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    AGE INT NOT NULL,
    BLOOD_GROUPr VARCHAR(10) NOT NULL,
    Gender VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASS_WORD VARCHAR(255) NOT NULL,
    phoneR VARCHAR(20) NOT NULL,
    ADD_RESSr TEXT NOT NULL,
    ZIP_CODE VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS organ_requests (
    REQUEST_ID INT AUTO_INCREMENT PRIMARY KEY,
    REGISTRATION_ID INT,
    phoneN VARCHAR(20),
    ADD_RESSn TEXT,
    BLOOD_GROUPn VARCHAR(10),
    REQUEST_TYPE VARCHAR(50), -- e.g. Kidney, Liver
    QUANTITY INT,
    REQUEST_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (REGISTRATION_ID) REFERENCES registration(REGISTRATION_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS donor (
    DONOR_ID INT AUTO_INCREMENT PRIMARY KEY,
    REGISTRATION_ID INT,
    WEIGHT FLOAT,
    BMI FLOAT,
    OPERATION_TYPE VARCHAR(50),
    OPERATION_DESC TEXT,
    DISEASE_TYPE VARCHAR(50),
    DISEASE_DESC TEXT,
    ACCIDENT_TYPE VARCHAR(50),
    ACCIDENT_DESC TEXT,
    FOREIGN KEY (REGISTRATION_ID) REFERENCES registration(REGISTRATION_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS donation_record (
    RECORD_ID INT AUTO_INCREMENT PRIMARY KEY,
    REGISTRATION_ID INT,
    BLOOD_GROUPd VARCHAR(10),
    QUANTITYd INT,
    last_donated DATE,
    FOREIGN KEY (REGISTRATION_ID) REFERENCES registration(REGISTRATION_ID) ON DELETE CASCADE
);
